### PR TITLE
Change action buttons to be "Continue" only

### PR DESCRIPTION
**Pull request by danieljimeneznz**

### CODE REVIEW

**Comment by mingnz** [comment]
In Spanish?

**Comment by mingnz** [comment]
> In Spanish?

Oh I only looked at the es file lol

**Review by mingnz — APPROVED** [review]
I don't think I have the full expertise to critique this, but looks fine?

**Comment by danieljimeneznz** [comment]
> I don't think I have the full expertise to critique this, but looks fine?

I'll walk you thru it a bit later 😄

**Pull request merged**
